### ISSUE TITLE
Could you add a readme file?

### ISSUE THREAD

**Issue by yangzhao1230** [hytracen/Thy-RayTracer#1]
Hi hytracen:

Thanks for your good work. But I wonder would you add a readme file to guide me to run your code?

**Comment by hytracen** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hytracen/Thy-RayTracer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 下午4:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[hytracen/Thy-RayTracer] Could you add a readme file? (Issue #1)





 
Hi hytracen:
 
Thanks for your good work. But I wonder would you add a readme file to guide me to run your code?

**Comment by hytracen** [comment]
别慌，还没写完
